### ISSUE TITLE
Catalina: The workflow you are trying to import is invalid.

### ISSUE THREAD

**Issue by rbadapanda** [AlexMartinFR/mojave-alfred-accented-themes#5]
Importing the workflow in alfred 4 throws error:

"The workflow you are trying to import is invalid."

**Comment by alexmartinfr** [comment]
Hi!

Everything works fine here and on a clean install as well.

Let's try to solve your issue:

- Please click [this download link](https://github.com/AlexMartinFR/mojave-alfred-accented-themes/releases/download/v1.2.1/Mojave-Themes-Switcher.alfredworkflow). Don't open it with *Archive Utility* or similar software, just **download it** straight to your computer.

- You should end up with a `Mojave-Themes-Switcher.alfredworkflow` file in your download folder.

- Double click it to install the workflow.

Feel free to take and post screenshots of the steps you took if this doesn't work 🙂


Also, can you try installing this other workflow on your machine to see if you encounter the same issue?
[https://www.packal.org/workflow/search-apple-notes](https://www.packal.org/workflow/search-apple-notes)

**Comment by rbadapanda** [comment]
![Screen Shot 2020-08-23 at 9 19 13 AM](https://user-images.githubusercontent.com/6469237/90983363-6a1aa000-e522-11ea-86c1-ecd86105556c.png)

Actually the issue is not with this particular workflow. I am hitting the same issue on the one you shared as well. however I am able to install the workflows from the '
![Plus Icon from inside the Alfred](https://user-images.githubusercontent.com/6469237/90983403-bf56b180-e522-11ea-891a-81ce713662c2.png)


Do you have any suggestions as to how I can debug the issue?

**Comment by alexmartinfr** [comment]
If you can't install any workflow on your Alfred copy, I think you should contact the Alfred support first.
Sorry for not being more helpful, I don't see what's wrong here.

Hope they'll be able to help you 🙂
